### PR TITLE
fix: set correct wrapper classes when there are autosize signals

### LINKED ISSUE #584: Use auto height on chart-wrapper div
Hello; Thanks for your time.

I don't know when this changed, but I recently discovered that the latest `vega-*` releases automatically set `div.chart-wrapper {height: 100%}` which has the effect of leaving a large blank area underneath the visible chart area. I can customize this from [Oz](https://github.com/metasoarous/oz) via my own stylesheets, but this may catch users offguard who opt out of these styles, or presumably who are using vega outside of Oz. Please consider switching back to the previous behavior.

Thanks again!

### PR DESCRIPTION
**Pull request by domoritz**
Fixes #584 

cc @metasoarous

### CODE REVIEW

File: src/embed.ts [hunk 1]
```diff
@@ -366,6 +357,17 @@ async function _embed(
...
   });
 
+  view.addSignalListener('autosize', (_, autosize: Exclude<AutoSize, string>) => {
+    const {type} = autosize;
+    container.classList.remove('fit-x', 'fit-y');
+    if (type == 'fit' || type == 'fit-x') {
+      container.classList.add('fit-x');
+    }
+    if (type == 'fit' || type == 'fit-y') {
+      container.classList.add('fit-y');
```
Comment (haldenl) [inline src/embed.ts:367]: Looks good. Just curious, do you know how the browser prevents flickering from the rapid remove / add of classes? Assuming there is some mechanism that executes blocks of CSS updates?

**Review by haldenl — APPROVED** [review]

File: src/embed.ts (hunk 1 above)
Comment (domoritz) [reply src/embed.ts:367]: I don't think there are rapid updates, are there? I would expect a few updates in a while.
